export HOMEBREW_CASK_OPTS='--appdir=/Applications'
HOMEBREW_NO_ANALYTICS=1

# go
export GOPATH=$HOME/code/go
export PATH=$PATH:$GOPATH/bin

# elixir
export PATH="$PATH:/usr/local/bin/elixir"

# rust
export PATH="$HOME/.cargo/bin:$PATH"

# NVM
export NVM_DIR="$HOME/.nvm"
