# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="dracula"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(zsh-syntax-highlighting)

# User configuration

source $ZSH/oh-my-zsh.sh

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

# Load NVM
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Autocomplete selected directories without need for cd
setopt auto_cd
cdpath=(. $HOME/github $HOME/Documents/projects )

# set default command line editor
export EDITOR=/usr/local/bin/nvim

# remove beeps
setopt no_beep

# ctrl-D doesn't close terminal window
stty eof ''

DISABLE_UPDATE_PROMPT=true
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
